sudo: required
dist: trusty
language: node_js
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - node_modules
install:
  - travis_retry npm install -g bower polymer-cli web-component-tester
  - travis_retry npm install
script:
  - travis_retry xvfb-run npm test
